---
title: "Reproducible Research: Peer Assessment 1"
author: "Flavius Popan"
date: "October 15, 2015"
output: 
html_document:
keep_md: true
---


## Loading and preprocessing the data
```{r preprocess, echo=TRUE}
## Extract the csv from the zip if it hasn't been done already
if (!file.exists("activity.csv")) {unzip("activity.zip")}

## Load the csv file as a dataset
activity_pre <- read.csv("activity.csv")

## Remove the NAs
activity <- activity_pre[with(activity_pre,{!(is.na(steps))}),]
```


## What is mean total number of steps taken per day?
```{r totalsteps, echo=TRUE}
## Calculate total number of steps taken daily
daily_steps <- aggregate(activity$steps,by=list(activity$date),sum)

## Rename the columns to something more useful
names(daily_steps) <- c("date", "steps")

## Display the data
head(daily_steps)

## Make a histogram of step frequency
hist(daily_steps$steps, main="Total Daily Steps", 
     xlab="Daily Steps")

## Display the mean & median steps
mean(daily_steps$steps)
median(daily_steps$steps)
```

**Mean: 10,766.19 - Median: 10,765**

## What is the average daily activity pattern?
```{r activitypattern, echo=TRUE}
## Aggregate the steps into intervals by mean
interval <- aggregate(steps ~ interval, activity, mean)

## Plot time series
plot(interval$interval, interval$steps, type='l', 
     main="Average Steps Across All Days", xlab="Interval", 
     ylab="Average Steps")

# Get max step row
max <- which.max(interval$steps)

# Find interval from max
interval[max, ]
```

**Interval 835 has the highest number of steps on average (206.16)**


## Imputing missing values
```{r missingvalues, echo=TRUE}

```


## Are there differences in activity patterns between weekdays and weekends?
```{r}

```
